// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddClipToHistory(arg1, arg2) {
  return window['go']['main']['App']['AddClipToHistory'](arg1, arg2);
}

export function GetClipboardHistory() {
  return window['go']['main']['App']['GetClipboardHistory']();
}

export function GetPhoneAuthToken() {
  return window['go']['main']['App']['GetPhoneAuthToken']();
}

export function GetServerInfo() {
  return window['go']['main']['App']['GetServerInfo']();
}

export function RestoreFromHistory(arg1) {
  return window['go']['main']['App']['RestoreFromHistory'](arg1);
}

export function Shutdown(arg1) {
  return window['go']['main']['App']['Shutdown'](arg1);
}

export function Startup(arg1) {
  return window['go']['main']['App']['Startup'](arg1);
}
