// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {clipboardMng} from '../models';
import {context} from '../models';

export function AddClipToHistory(arg1:string,arg2:string):Promise<void>;

export function GetClipboardHistory():Promise<Array<clipboardMng.Item>>;

export function GetPhoneAuthToken():Promise<string>;

export function GetServerInfo():Promise<Record<string, string>>;

export function RestoreFromHistory(arg1:number):Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
